services:
  - type: worker
    name: dlive-calls-bot-ws
    env: node
    autoDeploy: true
    plan: starter
    buildCommand: npm install --omit=dev
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: DLIVE_CHANNEL
        sync: false
      - key: CALLS_BASE_URL
        value: https://calls-bot.onrender.com
      - key: CALLS_ENDPOINT
        value: /api/calls
      - key: CALLS_SHARED_SECRET
        sync: false
